name: noaaplotter
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=3.9
  - numpy>=2.2
  - pandas>=2.2
  - python>=3.10
  - requests
  - joblib>=1.4
  - tqdm>=4.67
  - geemap>=0.35
